# Use the official Alpine Linux as a parent image
FROM alpine:latest

# Install dependencies
# Update the package list
RUN apk update

# Install dotnet
#! add later

# Install PHP
RUN apk add --no-cache php

# Install Python
RUN apk add --no-cache python3

# Install Node.js
RUN apk add --no-cache nodejs

# Install npm
RUN apk add --no-cache npm

# Install Git
RUN apk add --no-cache git

# Install Nginx
RUN apk add --no-cache nginx

# Install gettext
RUN apk add --no-cache gettext

# Copy the Nginx configuration template
COPY nginx.conf.template /etc/nginx/nginx.conf.template

# Create directories
RUN mkdir -p /app/src /app/config

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Expose port 80
EXPOSE 80

# Define the command to run the application
CMD envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'